# Deploy to EBS on push to master

name: EBS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --prefix client
    - run: npm run --prefix client build
    - run: git config --global user.email "ramarquez1992@gmail.com"
    - run: git config --global user.name "GitHub Workflow"
    - run: git add .
    - run: git commit -am "adding client/build/"
    - name: AWS Elastic Beanstalk cli
      uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: deploy ${{ secrets.AWS_ENV_NAME }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
